# SPDX-FileCopyrightText: 2025 The MALINA development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "malina"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"                                                                       # Needs to be checked later
description = "Create replicable and unique malware analysis laboratories from configuration"
documentation = "https://AntwortEinesLebens.github.io/MALINA/"
repository = "https://github.com/AntwortEinesLebens/MALINA/"
license = "GPL-3.0-or-later"
keywords = ["malware", "laboratory", "blueteam", "hypervisors"]
categories = ["command-line-utilities", "security", "virtualization"]

[dependencies]
toml = { version = "0.9.11" }
clap = { version = "4.5.58", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
virt = { version = "0.4.3" }
miette = { version = "7.6.0", features = ["fancy"] }
