# SPDX-FileCopyrightText: 2025 The MALINA development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "malina"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
authors = ["The MALINA development team"]
description = "Create replicable and unique malware analysis laboratories from configuration"
documentation = "https://AntwortEinesLebens.github.io/MALINA/"
repository = "https://github.com/AntwortEinesLebens/MALINA/"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = [
  "malware",
  "analysis",
  "laboratory",
  "security",
  "cli",
  "blueteam",
  "hypervisors",
]
categories = [
  "command-line-utilities",
  "development-tools",
  "security",
  "virtualization",
]

[dependencies]
tera = { version = "=1.20.1" }
clap = { version = "=4.6.1", features = ["derive"] }
clap_complete = { version = "=4.6.5" }
miette = { version = "=7.6.0", features = ["fancy"] }
thiserror = { version = "=2.0.18" }
log = { version = "=0.4.29" }
env_logger = { version = "=0.11.10" }
owo-colors = { version = "=4.3.0", features = ["supports-colors"] }
toml-span = { version = "=0.7.1" }
regex = { version = "=1.12.3" }
sysinfo = { version = "=0.39.2" }
virt = { version = "=0.4.3" }
futures = { version = "=0.3.32" }
tokio = { version = "=1.52.3", features = ["rt", "sync", "rt-multi-thread"] }
hadris-iso = { version = "=1.1.2" }
base64 = { version = "=0.22.1" }
serde_yaml = { version = "=0.9.34" }
serde_json = { version = "=1.0.149" }
