# SPDX-FileCopyrightText: 2025 The MALINA development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "malina"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["The MALINA development team"]
description = "Create replicable and unique malware analysis laboratories from configuration"
documentation = "https://AntwortEinesLebens.github.io/MALINA/"
repository = "https://github.com/AntwortEinesLebens/MALINA/"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = [
  "malware",
  "analysis",
  "laboratory",
  "security",
  "cli",
  "blueteam",
  "hypervisors",
]
categories = [
  "command-line-utilities",
  "development-tools",
  "security",
  "virtualization",
]

[dependencies]
clap = { version = "=4.5.60", features = ["derive"] }
clap_complete = { version = "=4.5.66" }
miette = { version = "=7.6.0", features = ["fancy"] }
thiserror = { version = "=2.0.18" }
log = { version = "=0.4.29" }
env_logger = { version = "=0.11.9" }
owo-colors = { version = "=4.3.0", features = ["supports-colors"] }
serde = { version = "=1.0.228", features = ["derive"] }
toml = { version = "=1.0.6+spec-1.1.0" }
