version = "1.0"

[laboratory]
name = "test-lab"

[[machines]]
identifier = "vm1"
name = "VM1"

[machines.hardware]
cpus = 2
memory_megabyte = 4096

[machines.operating_system]
family = "linux"
distribution = "debian"
version = "12"
image_path = "./test.qcow2"

[[machines]]
identifier = "vm2"
name = "VM2"

[machines.hardware]
cpus = 2
memory_megabyte = 8196

[machines.operating_system]
family = "linux"
distribution = "fedora"
version = "40"
image_path = "./test.qcow2"
