site_name: MALINA - Modular Automated Laboratories for Investigating Nefarious Artifacts
site_description: Deploy and manage stealthy, reproducible malware analysis laboratories from configuration files
site_author: The MALINA development team
copyright: 'Copyright &copy; 2025 The MALINA development team'
# Repository configuration
repo_name: MALINA
repo_url: https://github.com/AntwortEinesLebens/MALINA

# Navigation structure
nav:
  - Home: index.md
  - Installation: installation.md
  - Laboratory file: 
      - ./configuration/configuration.md
      - Generate:
          - ./configuration/configuration.md
          - Cloudbase-init: ./configuration/cloudbaseinit.md
          - Cloud-init: ./configuration/cloudinit.md
  - Usage Guide: usage.md
  - Patches : ./patches/patches.md
  - Troubleshooting: troubleshooting.md

# Theme configuration
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tooltips
  icon:
    logo: fontawesome/solid/flask

# Custom colors
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search:
      separator: '[\s\x00-\x1F]'
      lang: en
  - glightbox

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
      linenums: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Customization
extra:
  generator: false
